// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "hiperglm_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigenLeastSquaresWeighted
List eigenLeastSquaresWeighted(const Eigen::Map<MatrixXd>& X, const Eigen::Map<VectorXd>& y, const Eigen::Map<VectorXd>& w);
RcppExport SEXP _hiperglm_eigenLeastSquaresWeighted(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd>& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenLeastSquaresWeighted(X, y, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hiperglm_eigenLeastSquaresWeighted", (DL_FUNC) &_hiperglm_eigenLeastSquaresWeighted, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hiperglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
