# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenLeastSquaresWeighted <- function(X, y, w) {
    .Call(`_hiperglm_eigenLeastSquaresWeighted`, X, y, w)
}

